### ISSUE TITLE
"ValueError: Invalid rule" with easylist filter

### ISSUE THREAD

**Issue by darshandzend** [scrapinghub/adblockparser#10]
I intend to use [the easylist default filter](https://easylist.to/easylist/easylist.txt) to be used by splash, but when I try to do so, I get the following error:

```
2016-10-17 11:33:54+0000 [-] Log opened.
2016-10-17 11:33:54.636355 [-] Splash version: 2.2
2016-10-17 11:33:54.637039 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 16.1.1, Lua 5.2
2016-10-17 11:33:54.637173 [-] Python 3.4.3 (default, Oct 14 2015, 20:28:29) [GCC 4.8.4]
2016-10-17 11:33:54.637485 [-] Open files limit: 1048576
2016-10-17 11:33:54.638120 [-] Can't bump open files limit
2016-10-17 11:33:54.743707 [-] Xvfb is started: ['Xvfb', ':1', '-screen', '0', '1024x768x24']
2016-10-17 11:33:55.446450 [-] Traceback (most recent call last):
2016-10-17 11:33:55.446740 [-]   File "/app/bin/splash", line 4, in <module>
2016-10-17 11:33:55.448561 [-]     main()
2016-10-17 11:33:55.449293 [-]   File "/app/splash/server.py", line 372, in main
2016-10-17 11:33:55.450906 [-]     server_factory=server_factory,
2016-10-17 11:33:55.451930 [-]   File "/app/splash/server.py", line 273, in default_splash_server
2016-10-17 11:33:55.453654 [-]     allowed_schemes=allowed_schemes,
2016-10-17 11:33:55.454380 [-]   File "/app/splash/network_manager.py", line 58, in __init__
2016-10-17 11:33:55.456183 [-]     self.adblock_rules = AdblockRulesRegistry(filters_path, verbosity=verbosity)
2016-10-17 11:33:55.456661 [-]   File "/app/splash/request_middleware.py", line 161, in __init__
2016-10-17 11:33:55.458055 [-]     self._load(path)
2016-10-17 11:33:55.458534 [-]   File "/app/splash/request_middleware.py", line 204, in _load
2016-10-17 11:33:55.460139 [-]     max_mem=512*1024*1024,  # this doesn't actually use 512M
2016-10-17 11:33:55.460627 [-]   File "/usr/local/lib/python3.4/dist-packages/adblockparser/parser.py", line 301, in __init__
2016-10-17 11:33:55.462552 [-]     for r in rules
2016-10-17 11:33:55.463284 [-]   File "/usr/local/lib/python3.4/dist-packages/adblockparser/parser.py", line 299, in <listcomp>
2016-10-17 11:33:55.464906 [-]     r for r in (
2016-10-17 11:33:55.465371 [-]   File "/usr/local/lib/python3.4/dist-packages/adblockparser/parser.py", line 301, in <genexpr>
2016-10-17 11:33:55.466984 [-]     for r in rules
2016-10-17 11:33:55.467492 [-]   File "/usr/local/lib/python3.4/dist-packages/adblockparser/parser.py", line 112, in __init__
2016-10-17 11:33:55.469439 [-]     self.regex = self.rule_to_regex(rule_text)
2016-10-17 11:33:55.469940 [-]   File "/usr/local/lib/python3.4/dist-packages/adblockparser/parser.py", line 221, in rule_to_regex
2016-10-17 11:33:55.471339 [-]     raise ValueError("Invalid rule")
2016-10-17 11:33:55.471969 [-] ValueError: Invalid rule
```

I'm using scrapinghub/splash:2.2 docker image. My dockerfile looks like the following:

```
FROM scrapinghub/splash:2.2

# Adblock filters
ENV FILTDIR="/etc/splash/ad-filters/"
RUN wget -P $FILTDIR http://easylist.to/easylist/easylist.txt         #Error on run
RUN wget -P $FILTDIR http://easylist.to/easylist/fanboy-social.txt    #No error on run

CMD ["--filters-path=/etc/splash/ad-filters"]
```

Apologies if this isn't the correct project to create this issue.

**Comment by kmike** [comment]
Could you try Splash 2.2.1?

**Comment by kmike** [comment]
This should be fixed in https://github.com/scrapinghub/adblockparser/issues/9

**Comment by darshandzend** [comment]
@kmike Works without problems with splash 2.2.1. Thanks.
